hostname sb012.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:b9:a3:22 brd ff:ff:ff:ff:ff:ff inet 10.3.81.92/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:feb9:a322/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:b9:a3:23 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:b9:a3:24 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:b9:a3:25 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:88:66:39:03:00:23:ba:71 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.92/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.92/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::8a66:3903:23:ba71/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:88:66:39:03:00:23:ba:72 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 04:35:53,982 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.92:33832'
2024-01-19 04:35:54,033 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.92:33615'
2024-01-19 04:35:55,523 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-ogp34w6i', purging
2024-01-19 04:35:55,524 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-rt149_fp', purging
2024-01-19 04:35:55,524 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-0sncy2mb', purging
2024-01-19 04:35:55,543 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-58yf9zks', purging
2024-01-19 04:36:06,296 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.92:43014
2024-01-19 04:36:06,296 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.92:40479
2024-01-19 04:36:06,297 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.92:43014
2024-01-19 04:36:06,297 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.92:40479
2024-01-19 04:36:06,297 - distributed.worker - INFO -           Worker name:         SLURMCluster-443-0
2024-01-19 04:36:06,297 - distributed.worker - INFO -           Worker name:         SLURMCluster-443-1
2024-01-19 04:36:06,297 - distributed.worker - INFO -          dashboard at:           10.3.89.92:36307
2024-01-19 04:36:06,297 - distributed.worker - INFO -          dashboard at:           10.3.89.92:38185
2024-01-19 04:36:06,297 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:36:06,297 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:36:06,297 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,297 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,297 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:36:06,297 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:36:06,297 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:36:06,297 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:36:06,297 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-cgi55a72
2024-01-19 04:36:06,297 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-mkbbwoi7
2024-01-19 04:36:06,297 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,297 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,373 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:36:06,373 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,374 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 04:36:06,377 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:36:06,377 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:36:06,378 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 05:38:08,557 - distributed.core - INFO - Event loop was unresponsive in Worker for 13.53s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 43 conformers. 
Generated 17 conformers. 
Removed 14 conformers. 
Removed 32 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:   9%|██                    | 1/11 [00:03<00:37,  3.70s/it]Optimising conformer:  18%|████                  | 2/11 [00:05<00:23,  2.56s/it]Optimising conformer:  27%|██████                | 3/11 [00:07<00:17,  2.21s/it]Optimising conformer:  36%|████████              | 4/11 [00:09<00:14,  2.14s/it]Optimising conformer:  45%|██████████            | 5/11 [00:10<00:11,  1.93s/it]Optimising conformer:  55%|████████████          | 6/11 [00:14<00:12,  2.50s/it]Optimising conformer:  64%|██████████████        | 7/11 [00:15<00:08,  2.13s/it]Optimising conformer:  73%|████████████████      | 8/11 [00:17<00:05,  1.86s/it]Optimising conformer:  82%|██████████████████    | 9/11 [00:19<00:04,  2.01s/it]Optimising conformer:  91%|███████████████████  | 10/11 [00:20<00:01,  1.81s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:22<00:00,  1.78s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:22<00:00,  2.04s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:02<00:05,  2.66s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:04<00:02,  2.00s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:06<00:00,  2.15s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:06<00:00,  2.18s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 103.8s.
TIME Completed the molecule generation in 104.6s.
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 5 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:02<00:04,  2.31s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:04<00:02,  2.45s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:07<00:00,  2.57s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:07<00:00,  2.52s/it]
2024-01-19 09:24:31,964 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.92:40012 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:32,220 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.92:40010 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:57,948 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:57,948 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:57,950 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.92:40479. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,950 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.92:43014. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,961 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.92:33615'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,962 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.92:33832'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,970 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:57,988 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:57,975 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:57,994 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:59,997 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 46.1s.
2024-01-19 09:25:00,702 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.92:33615'. Reason: nanny-close-gracefully
2024-01-19 09:25:02,378 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.92:33832'. Reason: nanny-close-gracefully
2024-01-19 09:25:02,380 - distributed.dask_worker - INFO - End worker
