hostname sb088.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:5c brd ff:ff:ff:ff:ff:ff inet 10.3.81.168/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c95c/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:5d brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:5e brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:5f brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:60 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.168/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.168/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f360/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:61 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 04:05:30,384 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.168:39090'
2024-01-19 04:05:30,421 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.168:35662'
2024-01-19 04:05:31,936 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-ssoeqdb2', purging
2024-01-19 04:05:31,937 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-y56_olec', purging
2024-01-19 04:05:40,702 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.168:46866
2024-01-19 04:05:40,703 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.168:38302
2024-01-19 04:05:40,703 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.168:46866
2024-01-19 04:05:40,703 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.168:38302
2024-01-19 04:05:40,703 - distributed.worker - INFO -           Worker name:          SLURMCluster-54-1
2024-01-19 04:05:40,703 - distributed.worker - INFO -           Worker name:          SLURMCluster-54-0
2024-01-19 04:05:40,703 - distributed.worker - INFO -          dashboard at:          10.3.89.168:36662
2024-01-19 04:05:40,703 - distributed.worker - INFO -          dashboard at:          10.3.89.168:42625
2024-01-19 04:05:40,703 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:05:40,703 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 04:05:40,703 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:40,703 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:40,703 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:05:40,703 - distributed.worker - INFO -               Threads:                          2
2024-01-19 04:05:40,704 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:05:40,704 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 04:05:40,704 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-j5q0eadu
2024-01-19 04:05:40,704 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-eg44nz1x
2024-01-19 04:05:40,704 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:40,704 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:45,727 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:05:45,727 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:45,728 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 04:05:45,781 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 04:05:45,782 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 04:05:45,782 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 04:18:05,568 - distributed.core - INFO - Event loop was unresponsive in Worker for 48.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 04:18:11,701 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 5 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 10 conformers. 
Removed 7 conformers. 
Generated 49 conformers. 
Removed 46 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
[W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  33%|███████▋               | 1/3 [00:04<00:08,  4.43s/it]Optimising conformer:  33%|███████▋               | 1/3 [00:05<00:11,  5.57s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:06<00:03,  3.02s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:07<00:03,  3.64s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:08<00:00,  2.35s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:08<00:00,  2.78s/it]
Optimising conformer: 100%|███████████████████████| 3/3 [00:10<00:00,  3.28s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:10<00:00,  3.46s/it]
TIME Completed the molecule generation in 96.0s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:22<00:44, 22.10s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:23<00:09,  9.78s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:25<00:00,  6.22s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:25<00:00,  8.42s/it]
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 81.0s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 17 conformers. 
Removed 12 conformers. 
Generated 48 conformers. 
Removed 37 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]Optimising conformer:  20%|████▌                  | 1/5 [00:03<00:12,  3.15s/it]Optimising conformer:  40%|█████████▏             | 2/5 [00:04<00:06,  2.22s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:06<00:04,  2.18s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:09<00:02,  2.21s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:12<00:00,  2.72s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:12<00:00,  2.55s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME Completed the molecule generation in 57.4s.
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]Optimising conformer:   9%|██                    | 1/11 [00:02<00:25,  2.54s/it]Optimising conformer:  18%|████                  | 2/11 [00:03<00:16,  1.79s/it]Optimising conformer:  27%|██████                | 3/11 [00:04<00:11,  1.45s/it]Optimising conformer:  36%|████████              | 4/11 [00:07<00:12,  1.75s/it]Optimising conformer:  45%|██████████            | 5/11 [00:08<00:08,  1.49s/it]Optimising conformer:  55%|████████████          | 6/11 [00:10<00:09,  1.94s/it]Optimising conformer:  64%|██████████████        | 7/11 [00:11<00:06,  1.65s/it]Optimising conformer:  73%|████████████████      | 8/11 [00:14<00:05,  1.88s/it]Optimising conformer:  82%|██████████████████    | 9/11 [00:15<00:03,  1.61s/it]Optimising conformer:  91%|███████████████████  | 10/11 [00:16<00:01,  1.44s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:18<00:00,  1.72s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:18<00:00,  1.71s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 103.4s.
TIME changed dir: 0.0s
Generated 42 conformers. 
Removed 34 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]Optimising conformer:  12%|██▉                    | 1/8 [00:03<00:26,  3.85s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:08<00:24,  4.16s/it]Optimising conformer:  38%|████████▋              | 3/8 [00:12<00:20,  4.00s/it]Optimising conformer:  50%|███████████▌           | 4/8 [00:15<00:15,  3.97s/it]Optimising conformer:  62%|██████████████▍        | 5/8 [00:19<00:11,  3.68s/it]Optimising conformer:  75%|█████████████████▎     | 6/8 [00:21<00:06,  3.19s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:23<00:02,  2.90s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:27<00:00,  3.25s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:27<00:00,  3.46s/it]
2024-01-19 09:24:31,957 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.168:49550 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:32,085 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.168:49552 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:37,333 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:37,333 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:37,334 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.168:38302. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:37,334 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.168:46866. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:37,338 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.168:39090'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:37,339 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.168:35662'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:37,351 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:37,370 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:37,348 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:37,383 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:39,381 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 152.5s.
2024-01-19 09:24:39,384 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 91.0s.
2024-01-19 09:24:42,874 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.168:39090'. Reason: nanny-close-gracefully
2024-01-19 09:24:42,995 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.168:35662'. Reason: nanny-close-gracefully
2024-01-19 09:24:42,996 - distributed.dask_worker - INFO - End worker
